"""add auth_provider_id to users for supabase identity

Revision ID: 7106c42bd2dc
Revises: 7d55901b45f0
Create Date: 2026-09-10 13:40:22.316417
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7106c42bd2dc'
down_revision: Union[str, None] = '7d55901b45f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_auth_provider_id'), 'users', ['auth_provider_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_provider_id'), table_name='users')
    op.drop_column('users', 'auth_provider_id')
    # ### end Alembic commands ###
